'use client';
import {useCallback,useEffect,useState} from 'react';
import {Trophy,Users,ArrowUpRight,ArrowRight,LockKeyhole,Plus,Shuffle,Check,ChevronRight,Activity,Table2,LoaderCircle,ShieldCheck,RefreshCw} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import {standings,score,winner,validateSets,type Tournament,type Match,type Action} from '@/lib/tournament';
type Data={tournament:Tournament;version:number;isOrganizer:boolean;needsSetup:boolean;signedIn:boolean};
function Avatar({name,index=0}:{name:string;index?:number}){return <span className={'avatar av'+index%4}>{name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()}</span>}
export default function Arena(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('overview');
 const [modal,setModal]=useState<'players'|'setup'|'start'|'knockout'|null>(null),[names,setNames]=useState(''),[key,setKey]=useState('');
 const [editing,setEditing]=useState<Match|null>(null),[sets,setSets]=useState<string[][]>([['',''],['',''],['','']]);
 const [filter,setFilter]=useState('all');
 const load=useCallback(async()=>{try{const r=await fetch('/api/tournament',{cache:'no-store'});const d=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Falha de conexão.');}},[]);
 useEffect(()=>{load();const id=setInterval(load,20000);return()=>clearInterval(id)},[load]);
 async function mutate(action:Action){setBusy(true);try{const r=await fetch('/api/tournament',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...action,version:data?.version})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);await load();toast.success('Alterações salvas.');return true;}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível salvar.');return false;}finally{setBusy(false)}}
 const t=data?.tournament,done=t?.matches.filter(winner).length??0,total=t?.matches.length??0;
 const final=t?.matches.find(m=>m.group==='F'),champion=final&&winner(final);
 const name=(id:string)=>t?.players.find(p=>p.id===id)?.name??'A definir';
 const phase=champion?'Torneio encerrado':t?.knockout?'Fase eliminatória':t?.started?'Fase de grupos':'Inscrições abertas';
 function openMatch(m:Match){setEditing(m);setSets([0,1,2].map(i=>m.sets[i]?.map(String)??['','']));}
 function org(){if(data?.needsSetup)setModal('setup');else if(data?.isOrganizer){setNames(t!.players.map(p=>p.name).join('\n'));setModal('players')}else if(!data?.signedIn)window.location.href='/signin-with-chatgpt?return_to=%2F';else toast.info('Sua conta tem acesso somente à visualização.');}
 function renderMatch(m:Match){const s=score(m),win=winner(m);return <button key={m.id} className={'match-card '+(win?'finished':'')} disabled={!data?.isOrganizer||busy||(t?.knockout&&(m.group==='A'||m.group==='B'))} onClick={()=>openMatch(m)} aria-label={`${name(m.a)} contra ${name(m.b)}${win?', resultado registrado':', registrar resultado'}`}><div className="match-meta"><span>{m.group==='F'?'FINAL':m.group==='SF'?'SEMIFINAL':`GRUPO ${m.group} · RODADA ${m.round}`}</span><span className={win?'status-done':'status-next'}>{win?'Encerrada':'A jogar'}</span></div>{[m.a,m.b].map((id,i)=><div className={'match-player '+(win===id?'victor':'')} key={id}><span><Avatar name={name(id)} index={t!.players.findIndex(p=>p.id===id)}/>{name(id)}{win===id&&<Check size={15}/>}</span><strong>{win?s[i]:'–'}</strong></div>)}<div className="match-foot">{win?<span>{m.sets.map(s=>s.join('–')).join(' / ')}</span>:<span>Melhor de 3 sets</span>}{data?.isOrganizer&&<span>{win?'Ver resultado':'Registrar'} <ChevronRight size={14}/></span>}</div></button>}
 function renderGroup(group:'A'|'B'){const rows=standings(t!,group);return <section className="group-card"><div className="group-head"><span className={'group-letter '+(group==='B'?'blue':'')}>{group}</span><div><h3>Grupo {group}</h3><p>{rows.length} jogadores · todos contra todos</p></div><span className="small-pill">2 vagas</span></div><Table><TableHeader><TableRow><TableHead className="rank-cell">#</TableHead><TableHead>Jogador</TableHead><TableHead className="num">J</TableHead><TableHead className="num">V</TableHead><TableHead className="num">D</TableHead><TableHead className="num">SG</TableHead></TableRow></TableHeader><TableBody>{rows.map((p,i)=><TableRow key={p.id}><TableCell className={'rank-cell '+(i<2&&t?.started?'qualified':'')}>{String(i+1).padStart(2,'0')}</TableCell><TableCell><span className="table-player"><Avatar name={p.name} index={i}/><span>{p.name}</span></span></TableCell><TableCell className="num muted">{p.played}</TableCell><TableCell className="num bold">{p.wins}</TableCell><TableCell className="num muted">{p.losses}</TableCell><TableCell className="num">{p.sw-p.sl>0?'+':''}{p.sw-p.sl}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<div className="group-empty"><Users size={25}/><p>Os jogadores aparecerão aqui<br/>após o cadastro.</p></div>}<div className="group-bottom"><span className="qualification-mark"/> {t?.started?'1º e 2º avançam às semifinais':'Grupos definidos no sorteio'}</div></section>}
 return <div className="arena"><Toaster position="top-right" richColors/><header className="topbar"><a href="/" className="brand"><span className="brand-icon"><Table2 size={24}/></span><span>arena<span className="brand-light">solar</span><small>SIPAT · TÊNIS DE MESA</small></span></a><span className="edition">ESPORTE QUE CONECTA</span><Button variant="outline" className="organizer-btn" onClick={org} disabled={!data}><LockKeyhole size={16}/>{data?.isOrganizer?'Organizador':'Área do organizador'}</Button></header>
 <main><div className="page-heading"><div><div className="eyebrow">GRUPO SOLAR <span>/</span> TORNEIO DE TÊNIS DE MESA</div><h1>O próximo ponto<br className="mobile-break"/> é seu<span>.</span></h1><p>Os confrontos, a classificação e cada conquista do torneio.</p></div><div className="phase-badge"><span className="pulse"/>{phase}</div></div>
 {error&&<div className="error-box" role="alert">{error}<Button variant="outline" onClick={load}><RefreshCw size={16}/>Tentar novamente</Button></div>}
 {!data&&!error?<div className="loading"><LoaderCircle className="spin"/>Carregando o torneio…</div>:data&&t&&<>
 <div className="stats"><div><span className="stat-icon"><Users/></span><section><small>JOGADORES</small><strong>{String(t.players.length).padStart(2,'0')}<em>/ 12</em></strong></section></div><div><span className="stat-icon"><Table2/></span><section><small>GRUPOS</small><strong>02<em>fase inicial</em></strong></section></div><div><span className="stat-icon"><Activity/></span><section><small>PARTIDAS ENCERRADAS</small><strong>{String(done).padStart(2,'0')}<em>/ {total||'—'}</em></strong></section></div><div className="format-stat"><span className="stat-icon"><Trophy/></span><section><small>FORMATO DOS JOGOS</small><strong>MD3<em>2 sets para vencer</em></strong></section></div></div>
 <Tabs value={tab} onValueChange={setTab}><div className="nav-row"><TabsList variant="line" className="main-tabs"><TabsTrigger value="overview">Visão geral</TabsTrigger><TabsTrigger value="matches">Partidas <span className="count">{total}</span></TabsTrigger><TabsTrigger value="players">Jogadores</TabsTrigger><TabsTrigger value="bracket">Mata-mata</TabsTrigger></TabsList><span className="auto-update"><RefreshCw size={13}/> Atualização automática</span></div>
 <TabsContent value="overview"><div className="overview-layout"><div className="main-column"><div className="section-heading"><div><h2>Classificação dos grupos</h2><p>Acompanhe quem está na disputa pelas semifinais.</p></div><span className="outline-pill">FASE 01</span></div><div className="groups">{renderGroup('A')}{renderGroup('B')}</div><div className="table-key">J: jogos &nbsp; V: vitórias &nbsp; D: derrotas &nbsp; SG: saldo de sets</div><div className="section-heading next-heading"><div><h2>{champion?'Últimos resultados':'Próximos confrontos'}</h2><p>{t.started?'Cada partida aproxima você da decisão.':'Tudo pronto para o primeiro saque.'}</p></div><button className="text-link" onClick={()=>setTab('matches')}>Ver partidas <ArrowUpRight size={16}/></button></div>{t.started?<div className="match-grid">{(champion?t.matches.slice(-3):t.matches.filter(m=>!winner(m)).slice(0,4)).map(m=>renderMatch(m))}</div>:<div className="start-panel"><span className="start-icon"><Shuffle size={28}/></span><div><h3>O torneio começa com vocês.</h3><p>Cadastre de 4 a 12 jogadores e sorteie os grupos<br/>para gerar os confrontos automaticamente.</p></div>{data.isOrganizer?<Button className="primary-btn" onClick={()=>{setNames(t.players.map(p=>p.name).join('\n'));setModal(t.players.length?'start':'players')}}>{t.players.length?'Sortear e iniciar':'Cadastrar jogadores'}<ArrowRight size={17}/></Button>:<span className="waiting-label">Aguardando organização</span>}</div>}</div>
 <aside><div className="journey"><div className="journey-top"><Trophy size={22}/><span>RUMO AO TÍTULO</span></div><h2>{champion?name(champion):'Uma mesa.\nUm campeão.'}</h2><p>{champion?'Campeão do torneio. Parabéns pela conquista!':'Da fase de grupos ao último ponto.'}</p><div className="steps"><div className={t.started?'active':''}><span>01</span><section><b>Fase de grupos</b><small>2 grupos · todos contra todos</small></section>{t.knockout&&<Check size={17}/>}</div><div className={t.knockout?'active':''}><span>02</span><section><b>Semifinais</b><small>1º A × 2º B · 1º B × 2º A</small></section></div><div className={champion?'active':''}><span>03</span><section><b>Grande final</b><small>O encontro dos vencedores</small></section><Trophy size={17}/></div></div><div className="journey-progress"><span>Partidas concluídas<b>{total?Math.round(done/total*100):0}%</b></span><Progress value={total?done/total*100:0}/></div></div><div className="rules"><h3>Dentro das regras <ShieldCheck size={18}/></h3><p><b>Melhor de 3 sets</b><br/>Vence quem conquistar 2 sets.</p><p><b>11 pontos por set</b><br/>Sempre com 2 pontos de vantagem.</p><p><b>Desempate na classificação</b><br/>Vitórias → saldo de sets → saldo de pontos → ordem do sorteio.</p><div><LockKeyhole size={14}/> Resultados registrados pelo organizador.</div></div>{data.isOrganizer&&t.started&&!t.knockout&&<Button className="primary-btn full" disabled={!t.matches.every(winner)||busy} onClick={()=>setModal('knockout')}>Gerar semifinais<ArrowRight size={16}/></Button>}</aside></div></TabsContent>
 <TabsContent value="matches"><div className="section-heading"><div><h2>Todos os confrontos</h2><p>{data.isOrganizer?'Selecione uma partida para registrar ou corrigir o placar.':'Acompanhe o placar de cada partida.'}</p></div></div><Tabs value={filter} onValueChange={setFilter}><TabsList className="filters"><TabsTrigger value="all">Todas</TabsTrigger><TabsTrigger value="next">A jogar</TabsTrigger><TabsTrigger value="done">Encerradas</TabsTrigger><TabsTrigger value="A">Grupo A</TabsTrigger><TabsTrigger value="B">Grupo B</TabsTrigger></TabsList></Tabs><div className="all-matches">{t.matches.filter(m=>filter==='all'||filter==='next'&&!winner(m)||filter==='done'&&winner(m)||m.group===filter).map(m=>renderMatch(m))}</div>{!t.matches.filter(m=>filter==='all'||filter==='next'&&!winner(m)||filter==='done'&&winner(m)||m.group===filter).length&&<div className="empty-state"><Table2 size={35}/><h3>Nenhuma partida por aqui</h3><p>{t.started?'As partidas aparecerão conforme o torneio avançar.':'Os confrontos serão gerados após o sorteio dos grupos.'}</p></div>}</TabsContent>
 <TabsContent value="players"><div className="section-heading"><div><h2>Quem entra em quadra</h2><p>{t.players.length} de 12 vagas preenchidas.</p></div>{data.isOrganizer&&!t.started&&<Button className="primary-btn" onClick={()=>{setNames(t.players.map(p=>p.name).join('\n'));setModal('players')}}><Plus size={16}/>Cadastrar jogadores</Button>}</div><div className="player-grid">{t.players.map((p,i)=><div className="player-card" key={p.id}><Avatar name={p.name} index={i}/><div><h3>{p.name}</h3><p>{t.started?`Grupo ${p.group}`:'Inscrição confirmada'}</p></div><span className="player-number">{String(i+1).padStart(2,'0')}</span></div>)}</div>{!t.players.length&&<div className="empty-state"><Users size={35}/><h3>O primeiro jogador pode ser você.</h3><p>A organização ainda não cadastrou os participantes.</p></div>}{data.isOrganizer&&t.players.length>0&&!t.started&&<Button className="primary-btn" onClick={()=>setModal('start')}><Shuffle size={16}/>Sortear grupos e iniciar</Button>}</TabsContent>
 <TabsContent value="bracket"><div className="section-heading"><div><h2>O caminho até a taça</h2><p>Os dois melhores de cada grupo avançam. Todas as decisões em melhor de 3.</p></div></div><div className="bracket"><section><h3>SEMIFINAIS</h3>{t.matches.filter(m=>m.group==='SF').map(m=>renderMatch(m))}{!t.knockout&&['1º do Grupo A × 2º do Grupo B','1º do Grupo B × 2º do Grupo A'].map(x=><div className="placeholder-match" key={x}><b>{x}</b><p>Aguardando classificação dos grupos</p></div>)}</section><span className="bracket-arrow"><ChevronRight/></span><section><h3>GRANDE FINAL</h3>{final?renderMatch(final):<div className="placeholder-match"><b>Vencedor SF 1 × Vencedor SF 2</b><p>Aguardando as semifinais</p></div>}</section><div className="champion"><Trophy size={44}/><small>CAMPEÃO</small><h3>{champion?name(champion):'Quem fica com a taça?'}</h3></div></div>{data.isOrganizer&&t.started&&!t.knockout&&<Button className="primary-btn" disabled={!t.matches.every(winner)||busy} onClick={()=>setModal('knockout')}>Encerrar grupos e gerar semifinais</Button>}</TabsContent>
 </Tabs></>}
 <footer><span>arena<b>solar</b> <span>· SIPAT</span></span><p>Respeito em cada jogada. Integração em cada encontro.</p><span>MD3 · ATÉ 12 JOGADORES</span></footer></main>
 <Dialog open={modal!==null} onOpenChange={o=>{if(!o&&!busy)setModal(null)}}><DialogContent><DialogHeader><DialogTitle>{modal==='players'?'Jogadores do torneio':modal==='setup'?'Ativar sua área de organização':modal==='start'?'Vamos começar o torneio?':'Encerrar a fase de grupos?'}</DialogTitle><DialogDescription>{modal==='players'?'Digite um nome por linha. De 4 a 12 participantes.':modal==='setup'?'Vincule a organização à sua conta usando a chave recebida nesta conversa.':modal==='start'?'Os jogadores serão sorteados em dois grupos equilibrados. Após iniciar, a lista de participantes fica definida.':'Os dois melhores de cada grupo avançam. Após confirmar, os resultados dos grupos ficam bloqueados.'}</DialogDescription></DialogHeader>
 {modal==='players'&&<form onSubmit={async e=>{e.preventDefault();if(await mutate({type:'players',names:names.split('\n').map(n=>n.trim()).filter(Boolean)}))setModal(null)}}><label className="form-label" htmlFor="names">Nomes dos participantes</label><textarea id="names" required rows={10} value={names} onChange={e=>setNames(e.target.value)} placeholder={'Um jogador por linha'}/><div className="form-footer"><span>{names.split('\n').filter(n=>n.trim()).length}/12 participantes</span><Button className="primary-btn" disabled={busy}>{busy?'Salvando…':'Salvar jogadores'}</Button></div></form>}
 {modal==='setup'&&(data?.signedIn?<form onSubmit={async e=>{e.preventDefault();if(await mutate({type:'claim',key:key.trim()})){setKey('');setModal(null)}}}><label className="form-label" htmlFor="key">Chave de organização</label><Input id="key" type="password" required value={key} onChange={e=>setKey(e.target.value)} autoComplete="off"/><Button className="primary-btn full mt-4" disabled={busy}>Vincular minha conta</Button></form>:<a className="login-link" href="/signin-with-chatgpt?return_to=%2F" target="_top">Entrar com ChatGPT <ArrowRight size={16}/></a>)}
 {(modal==='start'||modal==='knockout')&&<Button className="primary-btn" disabled={busy} onClick={async()=>{if(await mutate({type:modal==='start'?'start':'knockout'})){setModal(null);setTab(modal==='knockout'?'bracket':'overview')}}}>{busy?'Preparando…':'Confirmar e continuar'}</Button>}
 </DialogContent></Dialog>
 <Dialog open={!!editing} onOpenChange={o=>{if(!o&&!busy)setEditing(null)}}><DialogContent><DialogHeader><DialogTitle>Resultado da partida</DialogTitle><DialogDescription>Melhor de 3 sets. Deixe o 3º set vazio se a partida terminar em 2 × 0.</DialogDescription></DialogHeader>{editing&&<form onSubmit={async e=>{e.preventDefault();try{const v=sets.filter(s=>s.some(x=>x!=='')).map(s=>s.map(x=>x===''?NaN:Number(x)));validateSets(v);if(await mutate({type:'result',id:editing.id,sets:v}))setEditing(null)}catch(e){toast.error(e instanceof Error?e.message:'Confira o placar.')}}}><div className="score-header"><b>{name(editing.a)}</b><span>×</span><b>{name(editing.b)}</b></div>{sets.map((s,i)=><div className="set-row" key={i}><Input aria-label={`${name(editing.a)}, set ${i+1}`} inputMode="numeric" type="number" min="0" max="999" value={s[0]} onChange={e=>setSets(old=>old.map((r,j)=>j===i?[e.target.value,r[1]]:r))}/><span>SET {i+1}</span><Input aria-label={`${name(editing.b)}, set ${i+1}`} inputMode="numeric" type="number" min="0" max="999" value={s[1]} onChange={e=>setSets(old=>old.map((r,j)=>j===i?[r[0],e.target.value]:r))}/></div>)}<Button className="primary-btn full mt-4" disabled={busy}>{busy?'Salvando…':'Salvar resultado'}</Button>{editing.sets.length>0&&<Button type="button" variant="ghost" className="full mt-2" disabled={busy} onClick={async()=>{if(await mutate({type:'result',id:editing.id,clear:true}))setEditing(null)}}>Remover resultado registrado</Button>}</form>}</DialogContent></Dialog>
 </div>
}
